[package]
name = "takumi"
version = "0.10.0"
edition = "2024"
license = "MIT"
description = "High-performance Rust library for generating images with CSS Flexbox-like layouts."
keywords = ["image", "css", "flexbox", "layout", "rendering"]
repository = "https://github.com/kane50613/takumi"
readme = "README.md"
exclude = ["benches/**/*"]
rust-version = "1.85.1"

[dependencies]
imageproc = "0.25"
merge = "0.2"
ts-rs = "11.0"
slotmap = "1.0"
rayon = "1.10"

[dependencies.base64]
version = "0.22"
optional = true

[dependencies.bytes]
version = "1.10"
optional = true

[dependencies.minreq]
version = "2.13"
features = ["https"]
optional = true

[dependencies.flate2]
version = "1.1"
optional = true

[dependencies.woff2-patched]
version = "0.4"
optional = true

[dependencies.lru]
version = "0.14"
optional = true

[dependencies.cosmic-text]
version = "0.14"
features = ["shape-run-cache"]

[dependencies.taffy]
version = "0.8"
features = ["serde"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.wasm-bindgen]
version = "0.2"
optional = true

[dependencies.image]
default-features = false
version = "0.25"
features = ["jpeg", "png", "webp"]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies.criterion]
version = "0.6"
features = ["html_reports"]
default-features = false

[[bench]]
name = "takumi"
harness = false
required-features = []

[features]
default = ["woff2", "woff", "image_data_uri", "http_image_store"]
wasm = ["dep:wasm-bindgen"]
image_data_uri = ["dep:base64"]
woff2 = ["dep:woff2-patched", "dep:bytes"]
woff = ["dep:flate2"]
http_image_store = ["dep:minreq", "dep:lru"]
