[package]
name = "takumi-napi-core"
version = "0.10.0"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
rayon = "1.10.0"

[dependencies.takumi]
path = "../takumi"
features = ["woff2", "woff", "image_data_uri"]
default-features = false

[dependencies.napi]
version = "3.0.0-beta.9"
default-features = false
features = ["napi10", "serde-json"]

[dependencies.napi-derive]
version = "3.0.0-beta.9"
features = ["type-def"]

[build-dependencies]
napi-build = "3.0.0-beta.0"
